[package]
name = "wasi-embedded-hal"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "2.4.2"
embedded-hal = "1.0.0"
lol_alloc = "0.4.1"
wit-bindgen-rt = "0.22.0"
